name: den
version: 0.1.3
author: Sean Eagan <seaneagan1@gmail.com>
description: A pubspec authoring tool.
homepage: https://github.com/seaneagan/den
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  ansicolor: any
  contrast: '>=0.1.1 <0.2.0'
  path: '>=1.3.0 <2.0.0'
  prompt: '>=0.1.7 <0.2.0'
  pub_package_data: any
  pub_semver: '>=1.0.0 <2.0.0'
  quiver: '>=0.18.2'
  source_span: any
  unscripted: '>=0.5.0 <0.6.0'
  which: '>=0.1.0 <0.2.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <12.0.0'
executables:
  den: null
